apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-pet
  namespace: pet
spec:
  selector:
    matchLabels:
      app: pet
  replicas: 5 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: pet
    spec:
      containers:
      - name: pet
        image: 861531569385.dkr.ecr.eu-west-2.amazonaws.com/k8s-pet:2

        ports:
        - containerPort: 80
